spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_room?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8081
browser:
  def-location: C:\Program Files\Mozilla Firefox\firefox.exe
  init-url: http://127.0.0.1:8081